CXX = C:/msys64/ucrt64/bin/clang++.exe
CXXFLAGS = -Iheader -Wall -Wextra -O3 -g -fsanitize=address -fsanitize=undefined
TARGET = Bastet_V2
SRCS = $(wildcard src/*.cpp)
HEADERS = $(wildcard header/*.h)
OBJS = $(patsubst src/%.cpp,obj/%.o,$(SRCS))

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^


obj/%.o: src/%.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
	del /Q /F $(TARGET).exe 
	del /Q /F obj\*.o